<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>UnitConverter.Contracts.Tests</AssemblyName>
    <RootNamespace>UnitConverter.Contracts.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UnitConverter.Common.Contracts\UnitConverter.Common.Contracts.csproj" />
    <ProjectReference Include="..\..\src\UnitConverter.UserManagement.Contracts\UnitConverter.UserManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\src\UnitConverter.UnitsDefinitions.Contracts\UnitConverter.UnitsDefinitions.Contracts.csproj" />
  </ItemGroup>

</Project>
