// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitConverter.UnitsDefinitions.DataAccess.Persistence;

#nullable disable

namespace UnitConverter.UnitsDefinitions.DataAccess.Migrations
{
    [DbContext(typeof(ConverterDbContext))]
    [Migration("20260603160712_InitialUnitDimensionSchema")]
    partial class InitialUnitDimensionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("UnitConverter.UnitsDefinitions.DataAccess.Persistence.Entities.UnitDimensionEntity", b =>
                {
                    b.Property<int>("DimensionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DimensionId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_UnitDimension_Name");

                    b.ToTable("UnitDimension", (string)null);
                });

            modelBuilder.Entity("UnitConverter.UnitsDefinitions.DataAccess.Persistence.Entities.UnitEntity", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DimensionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBaseUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MultiplierToBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OffsetToBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UnitId");

                    b.HasIndex("DimensionId")
                        .HasDatabaseName("IX_Unit_DimensionId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Unit_IsActive");

                    b.HasIndex("DimensionId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("UQ_Unit_Dimension_Symbol");

                    b.ToTable("Unit", null, t =>
                        {
                            t.HasCheckConstraint("CK_Unit_MultiplierToBase_Positive", "[MultiplierToBase] > 0");
                        });
                });

            modelBuilder.Entity("UnitConverter.UnitsDefinitions.DataAccess.Persistence.Entities.UnitEntity", b =>
                {
                    b.HasOne("UnitConverter.UnitsDefinitions.DataAccess.Persistence.Entities.UnitDimensionEntity", "Dimension")
                        .WithMany("Units")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Unit_Dimension");

                    b.Navigation("Dimension");
                });

            modelBuilder.Entity("UnitConverter.UnitsDefinitions.DataAccess.Persistence.Entities.UnitDimensionEntity", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
