<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>UnitConverter.UnitsDefinitions</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnitConverter.Common.Contracts\UnitConverter.Common.Contracts.csproj" />
    <ProjectReference Include="..\UnitConverter.UnitsDefinitions.Contracts\UnitConverter.UnitsDefinitions.Contracts.csproj" />
  </ItemGroup>

</Project>
